#52 makefile, re-organized: "TARGETS (UTILITY)".

diff --git a/scripts/makefile b/scripts/makefile
--- a/scripts/makefile
+++ b/scripts/makefile
@@ -57,28 +57,6 @@ unittest-verbose:
 codemetrics-verbose:
 	@clear; \
 	radon cc -a -s $(ROOT_DIR)/src/$(MODULE_NAME)*.py | grep -e '^[ ]*[CFM].*' | grep -v ' - A';
-commitavg-verbose:
-	@clear; \
-	python $(ROOT_DIR)/scripts/commitavgcalculator.py;
-check-pythonversion:
-	@clear; \
-	code="from nwpackageversions import LanguageChecker; print(LanguageChecker().get_version_status(required=(3, 12, 5)))"; \
-	python -c "$$code"
-check-requirements:
-	@clear; \
-	file_path="$(ROOT_DIR)/.devcontainer/Dockerfile"; \
-	code="from nwpackageversions import RequirementChecker; print(RequirementChecker().try_check(file_path = '$$file_path', only_stable_releases = True, sort_requirement_details = True))"; \
-	python -c "$$code";
-update-codecoverage:
-	@clear; \
-	cd $(ROOT_DIR)/tests/; \
-	coverage run -m unittest $(MODULE_NAME)tests.py > /dev/null 2>&1; \
-	value=$$(coverage report --include=$(MODULE_NAME).py | grep -oP 'TOTAL\s+\d+\s+\d+\s+\K\d+(?=%)'); \
-	if [ $$value -le 39 ]; then color="red"; elif [ $$value -le 69 ]; then color="orange"; else color="green"; fi; \
-	url="https://img.shields.io/badge/coverage-$${value}.0%25-$${color}"; \
-	echo "$$url" > $(ROOT_DIR)/codecoverage.txt; \
-	curl -s $$url -o $(ROOT_DIR)/codecoverage.svg; \
-	if [ $$? -eq 0 ]; then echo "[OK] $@: coverage badge updated successfully!"; else echo "[ERROR] $@: failed to update coverage badge."; fi;
 
 # TARGETS (CONCISE)
 type-concise:
@@ -119,6 +97,28 @@ codemetrics-concise:
 	if [[ "$$value" == *"A"* ]]; then echo "[OK] $@: the cyclomatic complexity is excellent ('$$value')."; else echo "[WARNING] $@: the cyclomatic complexity is not excellent ('$$value')"; fi;
 
 # TARGETS (UTILITY)
+calculate-commitavg:
+	@clear; \
+	python $(ROOT_DIR)/scripts/commitavgcalculator.py;
+check-pythonversion:
+	@clear; \
+	code="from nwpackageversions import LanguageChecker; print(LanguageChecker().get_version_status(required=(3, 12, 5)))"; \
+	python -c "$$code"
+check-requirements:
+	@clear; \
+	file_path="$(ROOT_DIR)/.devcontainer/Dockerfile"; \
+	code="from nwpackageversions import RequirementChecker; print(RequirementChecker().try_check(file_path = '$$file_path', only_stable_releases = True, sort_requirement_details = True))"; \
+	python -c "$$code";
+update-codecoverage:
+	@clear; \
+	cd $(ROOT_DIR)/tests/; \
+	coverage run -m unittest $(MODULE_NAME)tests.py > /dev/null 2>&1; \
+	value=$$(coverage report --include=$(MODULE_NAME).py | grep -oP 'TOTAL\s+\d+\s+\d+\s+\K\d+(?=%)'); \
+	if [ $$value -le 39 ]; then color="red"; elif [ $$value -le 69 ]; then color="orange"; else color="green"; fi; \
+	url="https://img.shields.io/badge/coverage-$${value}.0%25-$${color}"; \
+	echo "$$url" > $(ROOT_DIR)/codecoverage.txt; \
+	curl -s $$url -o $(ROOT_DIR)/codecoverage.svg; \
+	if [ $$? -eq 0 ]; then echo "[OK] $@: coverage badge updated successfully!"; else echo "[ERROR] $@: failed to update coverage badge."; fi;
 classdiagram-basic:
 	@clear; \
 	pyreverse $(ROOT_DIR)/src/$(MODULE_NAME).py -o mmd -d /home/$(MODULE_NAME)/; \
